apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: agandemajesty/devops-django-project:latest
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "1"
