apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-django-deployment
  labels:
    app: devops-django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-django-app
  template:
    metadata:
      labels:
        app: devops-django-app
    spec:
      containers:
        - name: devops-django-container
          image: agandemajesty/devops-django-project:latest
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "myproject.settings"
