apiVersion: v1
kind: Service
metadata:
  name: devops-django-service
spec:
  selector:
    app: devops-django-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
